- name: Demo on play level variables
  hosts: all
  vars:
    url: play.example.com
  tasks:
    - name: Print play level variable
      ansible.builtin.debug:
        msg: URL - {{ url }}

- name: Demo on file variables
  hosts: all
  vars_files:
    - exvars.yml
  tasks:
    - name: Print play level variable
      ansible.builtin.debug:
        msg: URL - {{ url }}

- name: Demo on task level variable
  hosts: all
  tasks:
    - name: Print task level variable
      ansible.builtin.debug:
        msg: URL - {{ url }}
      vars:
        url: task.example.com

- name: Demo on role level variable
  hosts: all
  vars:
    url_play: url_play.example.com
  roles:
    - sample

- name: Demo on register variables
  hosts: all
  tasks:
    - name: run uptime shell command
      ansible.builtin.shell: uptime
      register: output
    - name: print the shell output
      ansible.builtin.debug:
        msg: '{{ output }}'
